#!/usr/bin/env bash
# Regenerates Config/Secrets.xcconfig from .env so there's one source of truth for secrets.
# Run this after editing .env, then re-run `xcodegen generate` if the project needs regenerating.
set -euo pipefail
cd "$(dirname "$0")/.."

if [ ! -f .env ]; then
  echo "No .env found — copy .env.example to .env and fill in your Supabase values first." >&2
  exit 1
fi

# shellcheck disable=SC1091
set -a; source .env; set +a

: "${SUPABASE_URL:?SUPABASE_URL missing from .env}"
: "${SUPABASE_ANON_KEY:?SUPABASE_ANON_KEY missing from .env}"

# .xcconfig treats a literal `//` anywhere on a line as starting a comment, which would
# truncate a URL like https://foo.supabase.co after the scheme. The standard escape is an
# empty build-setting reference `$()` splitting the slashes so Xcode doesn't see `//`.
escaped_url=$(echo "$SUPABASE_URL" | sed 's#//#/$()/#')

mkdir -p Config
cat > Config/Secrets.xcconfig <<EOF
// Generated by scripts/sync-secrets.sh from .env — do not edit by hand, do not commit.
SUPABASE_URL = ${escaped_url}
SUPABASE_ANON_KEY = ${SUPABASE_ANON_KEY}
EOF

echo "Wrote Config/Secrets.xcconfig"
